### ISSUE TITLE
Larvae and pupae show up in caravans

### ISSUE THREAD

**Issue by draegon1993** [biomes-team/BiomesCaverns#14]
Larvae showing up in caravans have a high chance of being old enough to metamorphose. Pupae can also show up, it seems. Neither is good because then the animal never leaves.

**Comment by draegon1993** [comment]
Pupae should also be forbidden from spawning in manhunter events, only IF they don't spawn at the edge properly

**Comment by joseasoler** [comment]
To prevent an animal from appearing in caravans, removing its `<tradeTags>` section should work. Adding `<canArriveManhunter>false</canArriveManhunter>` to their Def should prevent them from spawning in manhunter events.
