### ISSUE TITLE
Jellypots in Ancient Dangers

### ISSUE THREAD

**Issue by draegon1993** [biomes-team/BiomesCaverns#22]
It seems like Jellypots and potentially other Caverns bugs are spawning in ancient dangers, and break out eventually, causing issues. We should prevent this from happening.

**Comment by joseasoler** [comment]
`ComplexThreatWorker_SleepingInsects` considers that any creature using insectoid meat is an insectoid. Fixing this issue requires replacing all instances of `<useMeatFrom>Megaspider</useMeatFrom>` with a different meat instance.

**Comment by joseasoler** [comment]
This commit in core should prevent jellypots from spawning in ancient dangers: https://github.com/biomes-team/BiomesCore/commit/cc89bcead0c3622aaf44b0ada9938126e9408bcb

As far as I could find, the only enemies that can spawn in ancient dangers are insectoid hives and mechanoids, but they should not spawn insects directly. Reporters might have been discussing ancient complexes instead. I am going to investigate those separately.
