### ISSUE TITLE
Certain animal meats need to be auto-disabled by default

### ISSUE THREAD

**Issue by draegon1993** [biomes-team/BiomesCaverns#67]
![image](https://github.com/biomes-team/BiomesCaverns/assets/8301936/665d5733-f3bd-48e2-a3c7-2200118d7ef1)

**Comment by LionelColaso** [comment]
I too Agree it would be better if all Insectoids have insect meat

**Comment by joseasoler** [comment]
All of these insects will now use insect meat instead of the implied meat definitions generated by rimworld before.
