### ISSUE TITLE
Heatwaves and Cold Snaps

### ISSUE THREAD

**Issue by draegon1993** [biomes-team/BiomesCaverns#7]
Apparently, they can happen naturally in cavern biomes. Other than SC this should NOT happen.

**Comment by joseasoler** [comment]
Fixed in the Biomes! Core repository: https://github.com/biomes-team/BiomesCore/commit/aeea3ff8eed5ebfe4fb1ebc18944ef99b06f0d85

I also disabled other similar events from both vanilla and VEE.
